export const initialState = {
  callList: [],
  status: null,
  error: null,
  numIsActiveNavBar: 4,
  filterList: [
    {
      id: 1,
      name: 'Все типы',
      isOpen: false,
      activeMenu: 0,
      menuList: ['Все типы', 'Входящие', 'Исходящие'],
    },
    {
      id: 2,
      name: 'Все сотрудники',
      isOpen: false,
      activeMenu: 0,
      menuList: ['Все сотрудники', 'Константин К', 'Полина З'],
    },
    {
      id: 3,
      name: 'Все звонки',
      isOpen: false,
      activeMenu: 0,
      menuList: [
        'Все звонки',
        'Все клиенты',
        'Новые клиенты',
        'Все исполнители',
        'Через приложение',
        'Прочие звонки',
      ],
    },
    {
      id: 4,
      name: 'Все источники',
      isOpen: false,
      activeMenu: 0,
      menuList: ['Все источники', 'Источник 1', 'Источник 2', 'Источник 3'],
    },
    {
      id: 5,
      name: 'Все оценки',
      isOpen: false,
      activeMenu: 0,
      menuList: [
        'Все оценки',
        'Распознать',
        'Скрипт не использован',
        'Плохо',
        'Хорошо',
        'Отлично',
        'Одна красная точка',
        'Две серых точки',
        'Три зеленых точки',
      ],
    },
    {
      id: 6,
      name: 'Все ошибки',
      isOpen: false,
      activeMenu: 0,
      menuList: [
        'Все ошибки',
        'Приветствие',
        'Имя',
        'Цена',
        'Скидка',
        'Предзаказ',
        'Благодарность',
        'Стоп слова',
      ],
    },
  ],
  records: [],
  callListCopyForFilter: [],
};
